export const themeColorData = [
  { name: "base-grey-00", value: "#ffffff" },
  { name: "base-grey-10", value: "#f4f4f4" },
  { name: "base-grey-20", value: "#e0e0e0" },
  { name: "base-grey-30", value: "#c6c6c6" },
  { name: "base-grey-40", value: "#a8a8a8" },
  { name: "base-grey-50", value: "#8d8d8d" },
  { name: "base-grey-60", value: "#6f6f6f" },
  { name: "base-grey-70", value: "#525252" },
  { name: "base-grey-80", value: "#393939" },
  { name: "base-grey-90", value: "#262626" },
  { name: "base-grey-100", value: "#161616" },
  { name: "base-coolGrey-00", value: "#ffffff" },
  { name: "base-coolGrey-10", value: "#f2f4f8" },
  { name: "base-coolGrey-20", value: "#dde1e6" },
  { name: "base-coolGrey-30", value: "#c1c7cd" },
  { name: "base-coolGrey-40", value: "#a2a9b0" },
  { name: "base-coolGrey-50", value: "#878d96" },
  { name: "base-coolGrey-60", value: "#697077" },
  { name: "base-coolGrey-70", value: "#4d5358" },
  { name: "base-coolGrey-80", value: "#343a3f" },
  { name: "base-coolGrey-90", value: "#21272a" },
  { name: "base-coolGrey-100", value: "#121619" },
  { name: "base-warmGrey-00", value: "#ffffff" },
  { name: "base-warmGrey-10", value: "#f7f3f2" },
  { name: "base-warmGrey-20", value: "#e5e0df" },
  { name: "base-warmGrey-30", value: "#cac5c4" },
  { name: "base-warmGrey-40", value: "#ada8a8" },
  { name: "base-warmGrey-50", value: "#8f8b8b" },
  { name: "base-warmGrey-60", value: "#726e6e" },
  { name: "base-warmGrey-70", value: "#565151" },
  { name: "base-warmGrey-80", value: "#3c3838" },
  { name: "base-warmGrey-90", value: "#272525" },
  { name: "base-warmGrey-100", value: "#171414" },
  { name: "base-blue-00", value: "#ffffff" },
  { name: "base-blue-10", value: "#edf5ff" },
  { name: "base-blue-20", value: "#d0e2ff" },
  { name: "base-blue-30", value: "#a6c8ff" },
  { name: "base-blue-40", value: "#78a9ff" },
  { name: "base-blue-50", value: "#4589ff" },
  { name: "base-blue-60", value: "#0f62fe" },
  { name: "base-blue-70", value: "#0043ce" },
  { name: "base-blue-80", value: "#002d9c" },
  { name: "base-blue-90", value: "#001d6c" },
  { name: "base-blue-100", value: "#001141" },
  { name: "base-orange-00", value: "#ffffff" },
  { name: "base-orange-10", value: "#fff2e8" },
  { name: "base-orange-20", value: "#ffd9be" },
  { name: "base-orange-30", value: "#ffb784" },
  { name: "base-orange-40", value: "#ff832b" },
  { name: "base-orange-50", value: "#eb6200" },
  { name: "base-orange-60", value: "#ba4e00" },
  { name: "base-orange-70", value: "#8a3800" },
  { name: "base-orange-80", value: "#5e2900" },
  { name: "base-orange-90", value: "#3e1a00" },
  { name: "base-orange-100", value: "#231000" },
  { name: "base-purple-00", value: "#ffffff" },
  { name: "base-purple-10", value: "#f6f2ff" },
  { name: "base-purple-20", value: "#e8daff" },
  { name: "base-purple-30", value: "#d4bbff" },
  { name: "base-purple-40", value: "#be95ff" },
  { name: "base-purple-50", value: "#a56eff" },
  { name: "base-purple-60", value: "#8a3ffc" },
  { name: "base-purple-70", value: "#6929c4" },
  { name: "base-purple-80", value: "#491d8b" },
  { name: "base-purple-90", value: "#31135e" },
  { name: "base-purple-100", value: "#1c0f30" },
  { name: "base-red-00", value: "#ffffff" },
  { name: "base-red-10", value: "#fff1f1" },
  { name: "base-red-20", value: "#ffd7d9" },
  { name: "base-red-30", value: "#ffb3b8" },
  { name: "base-red-40", value: "#ff8389" },
  { name: "base-red-50", value: "#fa4d56" },
  { name: "base-red-60", value: "#da1e28" },
  { name: "base-red-70", value: "#a2191f" },
  { name: "base-red-80", value: "#750e13" },
  { name: "base-red-90", value: "#520408" },
  { name: "base-red-100", value: "#2d0709" },
  { name: "base-teal-00", value: "#ffffff" },
  { name: "base-teal-10", value: "#d9fbfb" },
  { name: "base-teal-20", value: "#9ef0f0" },
  { name: "base-teal-30", value: "#3ddbd9" },
  { name: "base-teal-40", value: "#08bdba" },
  { name: "base-teal-50", value: "#009d9a" },
  { name: "base-teal-60", value: "#007d79" },
  { name: "base-teal-70", value: "#005d5d" },
  { name: "base-teal-80", value: "#004144" },
  { name: "base-teal-90", value: "#022b30" },
  { name: "base-teal-100", value: "#081a1c" },
  { name: "base-yellow-00", value: "#ffffff" },
  { name: "base-yellow-10", value: "#fcf4d6" },
  { name: "base-yellow-20", value: "#fddc69" },
  { name: "base-yellow-30", value: "#f1c21b" },
  { name: "base-yellow-40", value: "#d2a106" },
  { name: "base-yellow-50", value: "#b28600" },
  { name: "base-yellow-60", value: "#8e6a00" },
  { name: "base-yellow-70", value: "#684e00" },
  { name: "base-yellow-80", value: "#483700" },
  { name: "base-yellow-90", value: "#302400" },
  { name: "base-yellow-100", value: "#1c1500" },
  { name: "base-magenta-00", value: "#ffffff" },
  { name: "base-magenta-10", value: "#fff0f7" },
  { name: "base-magenta-20", value: "#ffd6e8" },
  { name: "base-magenta-30", value: "#ffafd2" },
  { name: "base-magenta-40", value: "#ff7eb6" },
  { name: "base-magenta-50", value: "#ee5396" },
  { name: "base-magenta-60", value: "#d02670" },
  { name: "base-magenta-70", value: "#9f1853" },
  { name: "base-magenta-80", value: "#740937" },
  { name: "base-magenta-90", value: "#510224" },
  { name: "base-magenta-100", value: "#2a0a18" },
  { name: "base-green-00", value: "#ffffff" },
  { name: "base-green-10", value: "#defbe6" },
  { name: "base-green-20", value: "#a7f0ba" },
  { name: "base-green-30", value: "#6fdc8c" },
  { name: "base-green-40", value: "#42be65" },
  { name: "base-green-50", value: "#24a148" },
  { name: "base-green-60", value: "#198038" },
  { name: "base-green-70", value: "#0e6027" },
  { name: "base-green-80", value: "#044317" },
  { name: "base-green-90", value: "#022d0d" },
  { name: "base-green-100", value: "#071908" },
  { name: "base-cyan-00", value: "#ffffff" },
  { name: "base-cyan-10", value: "#e5f6ff" },
  { name: "base-cyan-20", value: "#bae6ff" },
  { name: "base-cyan-30", value: "#82cfff" },
  { name: "base-cyan-40", value: "#33b1ff" },
  { name: "base-cyan-50", value: "#1192e8" },
  { name: "base-cyan-60", value: "#0072c3" },
  { name: "base-cyan-70", value: "#00539a" },
  { name: "base-cyan-80", value: "#003a6d" },
  { name: "base-cyan-90", value: "#012749" },
  { name: "base-cyan-100", value: "#061727" },
];

// export const displayFontData = [
//   { name: "Font Headline 1", value: FONTTYPES.headline1 },
//   { name: "Font Headline 2", value: FONTTYPES.headline2 },
//   { name: "Font Subheadline 1", value: FONTTYPES.subheadline1 },
//   { name: "Font Subheadline 2", value: FONTTYPES.subheadline2 },
//   { name: "Font Body L", value: FONTTYPES.bodyL },
//   { name: "Font Body 1", value: FONTTYPES.body1 },
//   { name: "Font Body 2", value: FONTTYPES.body2 },
//   { name: "Font Label 1", value: FONTTYPES.label1 },
//   { name: "Font Label 2", value: FONTTYPES.label2 },
//   { name: "Font Action 1", value: FONTTYPES.action1 },
//   { name: "Font Action 2", value: FONTTYPES.action2 },
//   { name: "Font Caption 1", value: FONTTYPES.caption1 },
//   { name: "Font Caption 2", value: FONTTYPES.caption2 },
//   { name: "Font Footnote 1", value: FONTTYPES.footnote1 },
//   { name: "Font Footnote 2", value: FONTTYPES.footnote2 },
// ];

// SYSTEM ERROR [0]
//
// ____________.PDDccodxOKX0b,________
// ___________.OXo;;,........_________
// ___________cNo ____________________
// __________.DD, ____________________
// __________cN0c:looolc;.____________
// _________.xWNDD0DDNWMWXk;__________
// __________',.......,lONMNd.________
// _____________________-lXMNc________
// ______________________.xMWl________
// ______________________.xMK,________
// ________:ol'__________cXXc_________
// ________KMMXo._____.,xDD,__________
// ________;kXWMXOdodxOOd;____________
// __________,ok0DD0Od:.______________
